### ISSUE TITLE
I think http://icanhazepoch.com/ is down

### ISSUE THREAD

**Issue by PhanaticD** [parallelblock/MCAuthenticator#35]
title says it all, so the plugin fails to start

**Comment by Ichbinjoe** [comment]
As is, if icanhazepoch.com fails to respond, the server will spit out a scary looking warning, however should start fine.

https://github.com/parallelblock/MCAuthenticator/blob/432afef2605718a7b45a446b69d8415ea623333f/bukkit/src/main/java/io/ibj/mcauthenticator/auth/RFC6238.java#L154

**Comment by astei** [comment]
MCAuthenticator's code to check the site didn't work, because it was using a default Java user-agent which Cloudflare (which, apparently, now hosts `icanhazepoch.com`) rejects.

I've changed the user-agent so it works now.
